### ISSUE TITLE
Fix and improve README

### ISSUE THREAD

**Issue by rafamizes** [dartoos-dev/callor#6]
Turn it more "elegant" by:
- [x] writing a better descripion of the package's purposes
- [x] placing the project logo as the top element
- [x] Initializing the _Getting Started_ section
- [x] EO Principles badge
- [x] Rultor badge
- [x] pub badge
- [x] license badge
- [x] lint badge
- [x] PDD badge
- [x] CI status badge
- [x] codecov badge
- [x] Hits-of-Code badge

**Comment by rafamizes** [comment]
![free-vector-red-green-ok-not-ok-icons-clip-art_117413_Red_Green_Ok_Not_Ok_Icons_clip_art_hight](https://user-images.githubusercontent.com/24878574/119563254-b2027800-bd7d-11eb-990f-e5602a0d77b7.png)

**Comment by rafamizes** [comment]
![green-tick-and-red-cross-checkmarks-line-icons-vector-27113946](https://user-images.githubusercontent.com/24878574/119563707-48cf3480-bd7e-11eb-8644-092e00282daf.jpg)

**Comment by 0pdd** [comment]
@rafamizes the puzzle [#8](https://github.com/dartoos-dev/callor/issues/8) is still not solved.
